### ISSUE TITLE
Issue with height of new Ped spawned

### ISSUE THREAD

**Issue by Xcalibur34** [najeetpie/nass_mechanic#1]
Hello, when I add a new location, the Ped spawns above the ground.  Any ideas as to why?  I copy and paste the proper vectors but can’t seem to adjust the height of the Ped spawned.  I’m sure it’s a simple fixed so hoping someone can point me in the right direction.  I tried a couple different areas around the map and get the same result.

**Comment by Lewiscottrell12** [comment]
Have you tried to edid the z vector of the coords?
